# Generated by Django 4.2.7 on 2024-01-07 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvserieswatchlist",
            options={"verbose_name_plural": "tv series watchlist"},
        ),
    ]
