# Generated by Django 4.2.4 on 2023-11-06 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorite",
            new_name="WatchList",
        ),
        migrations.AlterModelOptions(
            name="watchlist",
            options={"verbose_name_plural": "watchlist"},
        ),
    ]
