# Generated by Django 4.2.7 on 2024-01-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0002_alter_tvserieswatchlist_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("production_company_id", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "movie production companies",
            },
        ),
        migrations.CreateModel(
            name="TVSeriesProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("production_company_id", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "tv series production companies",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="production_company",
        ),
        migrations.RemoveField(
            model_name="tvseries",
            name="production_company",
        ),
        migrations.AddField(
            model_name="movie",
            name="production_companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                to="movie_search.movieproductioncompany",
            ),
        ),
        migrations.AddField(
            model_name="tvseries",
            name="production_companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="tvseries",
                to="movie_search.tvseriesproductioncompany",
            ),
        ),
    ]
