# Generated by Django 4.1.2 on 2022-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0002_remove_genre_genres_genre_name_alter_genre_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="tmdb_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="genre",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
