# Generated by Django 4.1.2 on 2022-11-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0003_genre_tmdb_id_alter_genre_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("provider_id", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
