# Generated by Django 4.2.7 on 2024-01-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movie_search",
            "0003_movieproductioncompany_tvseriesproductioncompany_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="tvseries",
            name="tmdb_id",
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
