# Generated by Django 4.1.2 on 2023-07-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0004_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name_plural": "genres"},
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="tmdb_id",
            new_name="genre_id",
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.PositiveSmallIntegerField(default=0)),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tagline", models.CharField(blank=True, max_length=200, null=True)),
                ("vote_count", models.PositiveSmallIntegerField(default=0)),
                ("vote_average", models.PositiveSmallIntegerField(default=0)),
                ("popularity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("runtime", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "production_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("overview", models.TextField(blank=True, default="", null=True)),
                ("budget", models.IntegerField(blank=True, default=0, null=True)),
                ("revenue", models.IntegerField(blank=True, default=0, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("homepage", models.CharField(blank=True, max_length=200, null=True)),
                ("video", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movie_search.genre"
                    ),
                ),
            ],
        ),
    ]
