# Generated by Django 4.1.2 on 2022-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0004_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("tagline", models.CharField(max_length=500)),
                ("vote_count", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
