# Generated by Django 4.1.2 on 2023-07-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "movie_search",
            "0005_alter_genre_options_rename_tmdb_id_genre_genre_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="video",
        ),
        migrations.AddField(
            model_name="movie",
            name="videos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie_search.video",
            ),
        ),
    ]
