# Generated by Django 4.2.7 on 2024-01-08 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0005_alter_movierecommendation_tmdb_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="tmdb_id",
            new_name="movie_id",
        ),
        migrations.RenameField(
            model_name="movierecommendation",
            old_name="tmdb_id",
            new_name="movie_id",
        ),
        migrations.RenameField(
            model_name="tvseries",
            old_name="tmdb_id",
            new_name="series_id",
        ),
        migrations.RenameField(
            model_name="tvseriesrecommendation",
            old_name="tmdb_id",
            new_name="series_id",
        ),
    ]
