# Generated by Django 4.1.2 on 2022-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0005_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
