# Generated by Django 4.1.2 on 2023-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0006_video_remove_movie_video_movie_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="videos",
        ),
        migrations.AddField(
            model_name="movie",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie_search.video"
            ),
        ),
    ]
