# Generated by Django 4.2.9 on 2024-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0007_alter_movie_movie_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierecommendation",
            name="movie_id",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="tvseries",
            name="series_id",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
