# Generated by Django 4.1.2 on 2023-07-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0007_remove_movie_videos_movie_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="videos",
        ),
        migrations.AddField(
            model_name="movie",
            name="videos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie_search.video",
            ),
        ),
    ]
