# Generated by Django 4.2.9 on 2024-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_search", "0008_alter_movierecommendation_movie_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="moviegenre",
            name="genre_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movieproductioncompany",
            name="production_company_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movieprovider",
            name="provider_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tvseries",
            name="vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tvseriesgenre",
            name="genre_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tvseriesproductioncompany",
            name="production_company_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tvseriesprovider",
            name="provider_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
