# Generated by Django 4.2.4 on 2023-09-04 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0008_remove_movie_videos_movie_videos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "videos"},
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="videos",
            new_name="video",
        ),
    ]
