# Generated by Django 4.2.4 on 2023-09-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0009_alter_video_options_rename_videos_movie_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="provider",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
