# Generated by Django 4.2.4 on 2023-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0010_alter_genre_name_alter_movie_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
