# Generated by Django 4.2.4 on 2023-09-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0012_alter_movie_popularity_alter_movie_vote_average"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="video",
        ),
        migrations.AddField(
            model_name="movie",
            name="video",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie_search.video"
            ),
        ),
    ]
