# Generated by Django 4.2.4 on 2023-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0013_remove_movie_video_movie_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="movie_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
