# Generated by Django 4.2.4 on 2023-09-07 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0014_video_movie_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="movie_id",
        ),
    ]
