# Generated by Django 4.2.4 on 2023-09-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0015_remove_video_movie_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.PositiveSmallIntegerField(default=0)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "recommendations",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="recommendation",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie_search.recommendation"
            ),
        ),
    ]
