# Generated by Django 4.2.4 on 2023-09-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie_search", "0016_recommendation_movie_recommendation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie_search.movie",
            ),
        ),
    ]
